name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Shreyansh"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "sunset"
  color: "orange"
